# Generated by Django 3.2.6 on 2021-09-08 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0004_insertgraph'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='insertgraph',
            table='insertgraph',
        ),
    ]
