# Generated by Django 3.2.6 on 2021-09-10 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0007_insertgraph2'),
    ]

    operations = [
        migrations.AddField(
            model_name='insertddl',
            name='yesno',
            field=models.CharField(default='Site1', max_length=300),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='insertddl',
            table='insertddl',
        ),
    ]
